version: "3.8"

x-hdc-common:
  &hdc-common
  build: 
    context: .
    dockerfile: one_hdc/Dockerfile
services:

  namenode:
    <<: *hdc-common
    container_name: namenode
    hostname: namenode
    environment:
      SERVICE: namenode
      HADOOP_CONF_DIR: /etc/hadoop
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
      - ./hadoop-config:/etc/hadoop
    networks:
      - bigdata

  datanode:
    <<: *hdc-common
    container_name: datanode
    hostname: datanode
    environment:
      SERVICE: datanode
      HADOOP_CONF_DIR: /etc/hadoop
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
      - ./hadoop-config:/etc/hadoop
    depends_on:
      - namenode
    networks:
      - bigdata

  resourcemanager:
    <<: *hdc-common
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      SERVICE: resourcemanager
      HADOOP_CONF_DIR: /etc/hadoop
    ports:
      - "8088:8088"
    volumes:
      - ./hadoop-config:/etc/hadoop
    depends_on:
      - namenode
    networks:
      - bigdata

  nodemanager:
    <<: *hdc-common
    container_name: nodemanager
    hostname: nodemanager
    environment:
      SERVICE: nodemanager
      HADOOP_CONF_DIR: /etc/hadoop
    volumes:
      - ./hadoop-config:/etc/hadoop
    depends_on:
      - resourcemanager
    networks:
      - bigdata

  spark-client:
    <<: *hdc-common
    container_name: spark-client
    hostname: spark-client
    environment:
      HADOOP_CONF_DIR: /etc/hadoop
      SPARK_MASTER: yarn
    volumes:
      - ./hadoop-config:/etc/hadoop
      - spark_jobs:/opt/spark/jobs
    networks:
      - bigdata
    command: tail -f /dev/null

volumes:
  hdfs_namenode:
  hdfs_datanode:
  spark_jobs:

networks:
  bigdata:
    driver: bridge



spark.sql("SHOW NAMESPACES").show()