version: "3"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870 # WEB UI
      - 9000:9000 # HDFS
      - 8088:8088   # YARN
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

  datanode:
    build: ./datanode
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata
  
  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

  nodemanager:
    build: ./nodemanager
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    networks:
      - bigdata
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  bigdata:
    external: true
    name: bigdata
    driver: bridge