version: "3"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870 # WEB UI
      # - 9000:9000 # HDFS
      - 8020:8020 # Бинарный порт HDFS RPC (Spark)
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - bigdata

  datanode:
    build: ./datanode
    container_name: datanode
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:8020"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - bigdata

  # YARN 
  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:8020 datanode:9864"
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
    env_file:
      - ./hadoop.env
    depends_on:
      - datanode
    networks:
      - bigdata

  nodemanager:
    build: ./nodemanager
    container_name: nodemanager
    restart: always
    environment:
      YARN_CONF_yarn_resourcemanager_address: "resourcemanager:8032"
      SERVICE_PRECONDITION: "namenode:9870 namenode:8020 datanode:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - resourcemanager
    networks:
      - bigdata
  
  spark-client:
    image: apache/spark:3.5.2
    container_name: spark-client
    environment:
      HADOOP_CONF_DIR: "/etc/hadoop"
      CORE_CONF_fs_defaultFS=: "dfs://namenode:8020"
    volumes:
      - :/opt/spark/jobs
    networks:
      - bigdata


volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  bigdata:
    external: true
    name: bigdata
    driver: bridge