########################################
# Iceberg extensions
########################################
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

########################################
# Catalog (REST)
########################################
spark.sql.catalog.lake=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lake.type=rest
spark.sql.catalog.lake.uri=http://rest-catalog:8181
spark.sql.catalog.lake.warehouse=s3a://warehouse/
spark.sql.catalog.lake.io-impl=org.apache.iceberg.hadoop.HadoopFileIO

########################################
# S3 / MinIO (S3A ONLY)
########################################
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.access.key=minio
spark.hadoop.fs.s3a.secret.key=minio12345
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

########################################
# Default catalog
########################################
spark.sql.defaultCatalog=lake

########################################
# Performance
########################################
spark.sql.shuffle.partitions=4

########################################
# Ivy cache
########################################
spark.jars.ivy=/tmp/.ivy2